### PR TITLE
add tomllint to projects section

### PR DESCRIPTION
**Pull request by gscho**
Added a project to the list.

### CODE REVIEW

**Comment by iology** [comment]
Not much different from my demo… Do you plan to only support TOML v1.0 in the future? l only maintain it for v0.4.0.

**Comment by gscho** [comment]
I disagree. Your demo shows the result of the parser. My website is for validating toml files.  I just wanted to add to your readme so you get credit for projects that use it. I can close this PR though. 

Also regarding toml 1.0: https://github.com/toml-lang/toml/issues/515

**Comment by iology** [comment]
My apologies if my rejection makes you a little unhappy. I don't know how many people are using exactly v0.4.0 rather than the latest v0.4.x. Also, the coming v1.0 which will be backward-compatible with v0.4.0, is not appealing to me and I had lost interest in promoting TOML years ago.

I suggest that you reserve your website and domain name for newer versions of TOML, unless you consider v0.4.0 a classic. ;-)

**Comment by gscho** [comment]
No worries.  Closing this PR.

**Pull request closed without merging**
